apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      application: springbootmongo
  template:
    metadata:
      labels:
        application: springbootmongo
    spec:
      containers:
      - name: spring-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo-service
        - name: MONGO_DB_USERNAME
          value: {{ .Values.mongo.username }}
        - name: MONGO_DB_PASSWORD
          value: {{ .Values.mongo.password }}
