apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mongo
  template:
    metadata:
      labels:
        application: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongo.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongo.password }}
