apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    application: mongo
  ports:
  - port: 27017
    targetPort: 27017
